language: python
python:
- '2.7'
script: tox
install: pip install tox
notifications:
  email:
  - m.mavlyutov@gmail.com
  - pupssman@gmail.com
deploy:
  provider: pypi
  user: mavlyutov
  password:
    secure: Aimu/wB30KsebRDHFLJdo5M6AsrKfhl6dL5wrdbFMeyklx6us18Rg6KD+KagjrHwVzxMifi2O/ael7YKSXN6nGXFo0VQCG3CNPYCnRvgLqh1IFTMvmVpWn3R4J7oi+UKc40Ipeaq+3yuZo+ssESXpjQIwIBMxifSA78Q3hqmgWA=
  on:
    tags: true
    all_branches: true
